replicaCount: 1

image:
  repository: mcr.microsoft.com/oss/nginx/nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

# Default. Overridden per environment from the ApplicationSet.
logLevel: info

nodeSelector:
  workload-type: userpool1

tolerations:
  - key: workload
    operator: Equal
    value: userpool1
    effect: NoSchedule

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi